### ISSUE TITLE
Doc-tests fail for custom CARGO_TARGET_DIR

### ISSUE THREAD

**Issue by dkellner** [goddtriffin/sitemap-rs#2]
**Describe the bug**

```
   Doc-tests sitemap-rs

running 1 test
test src/lib.rs - (line 7) ... FAILED

failures:

---- src/lib.rs - (line 7) stdout ----
Test executable failed (exit status: 101).

stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error encountered during write: No such file or directory (os error 2)', src/lib.rs:22:6
```

**To reproduce**
Steps to reproduce the behaviour:
1. `rm -r target`
2. `CARGO_TARGET_DIR=/tmp/foobar make test`

**Expected behaviour**
Doc-test should pass for all values of `CARGO_TARGET_DIR`.

**Possible solutions**
Sorted from easiest to probably "best" :wink:.

1. Just put the file in the project root and add it to `.gitignore`. But running tests altering the working directory is ugly.
2. Use something like [tempfile](https://crates.io/crates/tempfile).
3. Don't care about concrete files in `sitemap-rs` at all, but accept a generic `W: Write` (like `xml_builder::XML.generate`). Then the doc-test could just write to e.g. `Vec<u8>`.

**Comment by goddtriffin** [comment]
I really like the proposed 3rd solution. Making it generic over `W: Write` makes the most sense to me.
