### ISSUE TITLE
Other way to save the output

### ISSUE THREAD

**Issue by johansmitsnl** [goddtriffin/sitemap-rs#4]
**Is your feature request related to a problem? Please describe.**
I have generated a sitemap and I want to read it into `Bytes`. Now you can get a xml or write to a file output.

**Describe the solution you'd like**
Be able to do `to_string` or in my case to `Bytes`

**Comment by goddtriffin** [comment]
Would this PR solve your problem? https://github.com/goddtriffin/sitemap-rs/pull/3

**Comment by johansmitsnl** [comment]
Looks good, will check it later today and will close if it works. Thanks for the quick response.

**Comment by johansmitsnl** [comment]
@goddtriffin yes that worked perfectly. Thanks for the quick update.
